import { Container } from '@mui/material';
import { styled } from '@mui/system';
import Head from 'next/head';
import React from 'react';
import { Footer, Header } from '..';
// import useStyles from '../../utils/styles';

const StyledContainer = styled(Container)({
  minHeight: '90vh',
});

export default function Layout({ children }) {
  // const classes = useStyles()
  return (
    <>
      <Head>
        <title>Yosefus Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <StyledContainer>{children}</StyledContainer>
      <Footer />
    </>
  );
}
